export const Actions = {
    SET_SELECTED_VIDEO: 'SET_SELECTED_VIDEO',
    SET_SEARCH_RESULTS: 'SET_SEARCH_RESULTS',
    SET_SELECTED_CATEGORY: 'SET_SELECTED_CATEGORY',
    TOGGLE_SIDEBAR: 'TOGGLE_SIDEBAR',
    RESET_APP: 'RESET_APP',
}